### ISSUE TITLE
Not compatible with pylangacq version 0.13

### ISSUE THREAD

**Issue by Robinysh** [jacksonllee/pycantonese#25]
Code to reproduce
```
import pycantonese as pc                                                                                      
pc.word_segmentation.Segmenter()   

Traceback (most recent call last):                                                                                
  File "<stdin>", line 1, in <module>                                                                             
  File "/home/lib/python3.7/site-packages/pycantonese/word_segmentation.py", line 46, in __init__
    self.fit(hkcancor().sents())                                                                                  
  File "/home/lib/python3.7/site-packages/pycantonese/corpus.py", line 334, in hkcancor
    return CantoneseCHATReader(data_path, encoding="utf8")                                                        
  File "/home/lib/python3.7/site-packages/pycantonese/corpus.py", line 31, in __init__
    super(CantoneseCHATReader, self).__init__(*filenames, encoding=encoding)
TypeError: __init__() got an unexpected keyword argument 'encoding'     

```
Downgrading to pylangacq==0.12.0 works as a workaround

**Comment by jacksonllee** [comment]
Ah, I released pylangacq 0.13.0 three days ago, and am now working on upgrading pycantonese for the breaking changes like what you've shown here. I didn't realize in pycantonese I actually had [pylangacq>=0.12.0,<1.0.0](https://github.com/jacksonllee/pycantonese/blob/v3.1.0/setup.py#L52) -- my bad! I've just released [pycantonese 3.1.1](https://pypi.org/project/pycantonese/3.1.1/) to pin pylangacq at exact 0.12.0 for now.

Thank you for alerting me -- I've [added you in the acknowledgments](https://github.com/jacksonllee/pycantonese/commit/3f2919e05c79eafe81f9412a0a0663a319fe6402#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR173)!
